const ROLES = {
    ADMIN: 'admin',
    HR: 'hr',
    DIVISION_MANAGER: 'division_manager',
    OPERATOR: 'operator',
    VIEWER: 'viewer'
};

const HR_MANAGED_USER_ROLES = [ROLES.DIVISION_MANAGER, ROLES.OPERATOR, ROLES.VIEWER];
const EMPLOYEE_WRITE_ROLES = [ROLES.ADMIN, ROLES.HR, ROLES.DIVISION_MANAGER];
const READ_ROLES = [ROLES.ADMIN, ROLES.HR, ROLES.DIVISION_MANAGER, ROLES.OPERATOR, ROLES.VIEWER];
const WRITE_ROLES = [ROLES.ADMIN, ROLES.DIVISION_MANAGER, ROLES.OPERATOR];

module.exports = {
    ROLES,
    HR_MANAGED_USER_ROLES,
    EMPLOYEE_WRITE_ROLES,
    READ_ROLES,
    WRITE_ROLES
};
